export const asideBarList = [
  { name: "Dashboard", url: "/" },
  { name: "Customer", url: "/customer" },
  { name: "Delete Customer", url: "/delete-customer" },
  { name: "Customer Details", url: "/customer-details" },
  { name: "Customer List", url: "/customer-list" },
  { name: "Register", url: "/register" },
  { name: "Update", url: "/update" },
];
export const adminAsideList = [
  { name: "Dashboard", url: "/" },
  { name: "Customer", url: "/customer" },
  { name: "Delete Customer", url: "/delete-customer" },
  { name: "Customer Details", url: "/customer-details" },
  { name: "Customer List", url: "/customer-list" },
  { name: "Register", url: "/register" },
  { name: "Update", url: "/update" },
];

export const requiredRoles = [
  "admin",
  "manager",
  "sales_person",
  "support_agent",
  "marketing_specialist",
  "auditor",
];

export const administrationRoles = ["admin", "manager", "auditor"];

export const fakeUserData = [
  {
    name: "John Doe",
    company: "Tech Solutions Ltd.",
    phone_no: "+1-555-123-4567",
    email: "john.doe@example.com",
    role: "Manager",
  },
  {
    name: "Jane Smith",
    company: "Innovatech Inc.",
    phone_no: "+1-555-987-6543",
    email: "jane.smith@example.com",
    role: "Software Engineer",
  },
  {
    name: "Michael Brown",
    company: "Future Dynamics",
    phone_no: "+1-555-654-3210",
    email: "michael.brown@example.com",
    role: "Sales Representative",
  },
  {
    name: "Emily Davis",
    company: "Global Ventures",
    phone_no: "+1-555-789-1234",
    email: "emily.davis@example.com",
    role: "Product Designer",
  },
  {
    name: "Chris Johnson",
    company: "Pioneer Tech Group",
    phone_no: "+1-555-321-9876",
    email: "chris.johnson@example.com",
    role: "Data Scientist",
  },
  {
    name: "Sophia Wilson",
    company: "NextGen Innovations",
    phone_no: "+1-555-456-7890",
    email: "sophia.wilson@example.com",
    role: "HR Specialist",
  },
  {
    name: "David Lee",
    company: "Alpha Solutions",
    phone_no: "+1-555-876-5432",
    email: "david.lee@example.com",
    role: "Operations Manager",
  },
  {
    name: "Olivia Martinez",
    company: "Visionary Systems",
    phone_no: "+1-555-234-6789",
    email: "olivia.martinez@example.com",
    role: "Marketing Executive",
  },
  {
    name: "James Anderson",
    company: "Bright Tech Co.",
    phone_no: "+1-555-567-8901",
    email: "james.anderson@example.com",
    role: "DevOps Engineer",
  },
  {
    name: "Emma Thomas",
    company: "Greenfield Technologies",
    phone_no: "+1-555-678-1239",
    email: "emma.thomas@example.com",
    role: "Business Analyst",
  },
  {
    name: "John Doe",
    company: "Tech Solutions Ltd.",
    phone_no: "+1-555-123-4567",
    email: "john.doe@example.com",
    role: "Manager",
  },
  {
    name: "Jane Smith",
    company: "Innovatech Inc.",
    phone_no: "+1-555-987-6543",
    email: "jane.smith@example.com",
    role: "Software Engineer",
  },
  {
    name: "Michael Brown",
    company: "Future Dynamics",
    phone_no: "+1-555-654-3210",
    email: "michael.brown@example.com",
    role: "Sales Representative",
  },
  {
    name: "Emily Davis",
    company: "Global Ventures",
    phone_no: "+1-555-789-1234",
    email: "emily.davis@example.com",
    role: "Product Designer",
  },
  {
    name: "Chris Johnson",
    company: "Pioneer Tech Group",
    phone_no: "+1-555-321-9876",
    email: "chris.johnson@example.com",
    role: "Data Scientist",
  },
  {
    name: "Sophia Wilson",
    company: "NextGen Innovations",
    phone_no: "+1-555-456-7890",
    email: "sophia.wilson@example.com",
    role: "HR Specialist",
  },
  {
    name: "David Lee",
    company: "Alpha Solutions",
    phone_no: "+1-555-876-5432",
    email: "david.lee@example.com",
    role: "Operations Manager",
  },
  {
    name: "Olivia Martinez",
    company: "Visionary Systems",
    phone_no: "+1-555-234-6789",
    email: "olivia.martinez@example.com",
    role: "Marketing Executive",
  },
  {
    name: "James Anderson",
    company: "Bright Tech Co.",
    phone_no: "+1-555-567-8901",
    email: "james.anderson@example.com",
    role: "DevOps Engineer",
  },
  {
    name: "Emma Thomas",
    company: "Greenfield Technologies",
    phone_no: "+1-555-678-1239",
    email: "emma.thomas@example.com",
    role: "Business Analyst",
  },
  {
    name: "John Doe",
    company: "Tech Solutions Ltd.",
    phone_no: "+1-555-123-4567",
    email: "john.doe@example.com",
    role: "Manager",
  },
  {
    name: "Jane Smith",
    company: "Innovatech Inc.",
    phone_no: "+1-555-987-6543",
    email: "jane.smith@example.com",
    role: "Software Engineer",
  },
  {
    name: "Michael Brown",
    company: "Future Dynamics",
    phone_no: "+1-555-654-3210",
    email: "michael.brown@example.com",
    role: "Sales Representative",
  },
  {
    name: "Emily Davis",
    company: "Global Ventures",
    phone_no: "+1-555-789-1234",
    email: "emily.davis@example.com",
    role: "Product Designer",
  },
  {
    name: "Chris Johnson",
    company: "Pioneer Tech Group",
    phone_no: "+1-555-321-9876",
    email: "chris.johnson@example.com",
    role: "Data Scientist",
  },
  {
    name: "Sophia Wilson",
    company: "NextGen Innovations",
    phone_no: "+1-555-456-7890",
    email: "sophia.wilson@example.com",
    role: "HR Specialist",
  },
  {
    name: "David Lee",
    company: "Alpha Solutions",
    phone_no: "+1-555-876-5432",
    email: "david.lee@example.com",
    role: "Operations Manager",
  },
  {
    name: "Olivia Martinez",
    company: "Visionary Systems",
    phone_no: "+1-555-234-6789",
    email: "olivia.martinez@example.com",
    role: "Marketing Executive",
  },
  {
    name: "James Anderson",
    company: "Bright Tech Co.",
    phone_no: "+1-555-567-8901",
    email: "james.anderson@example.com",
    role: "DevOps Engineer",
  },
  {
    name: "Emma Thomas",
    company: "Greenfield Technologies",
    phone_no: "+1-555-678-1239",
    email: "emma.thomas@example.com",
    role: "Business Analyst",
  },
  {
    name: "John Doe",
    company: "Tech Solutions Ltd.",
    phone_no: "+1-555-123-4567",
    email: "john.doe@example.com",
    role: "Manager",
  },
  {
    name: "Jane Smith",
    company: "Innovatech Inc.",
    phone_no: "+1-555-987-6543",
    email: "jane.smith@example.com",
    role: "Software Engineer",
  },
  {
    name: "Michael Brown",
    company: "Future Dynamics",
    phone_no: "+1-555-654-3210",
    email: "michael.brown@example.com",
    role: "Sales Representative",
  },
  {
    name: "Emily Davis",
    company: "Global Ventures",
    phone_no: "+1-555-789-1234",
    email: "emily.davis@example.com",
    role: "Product Designer",
  },
  {
    name: "Chris Johnson",
    company: "Pioneer Tech Group",
    phone_no: "+1-555-321-9876",
    email: "chris.johnson@example.com",
    role: "Data Scientist",
  },
  {
    name: "Sophia Wilson",
    company: "NextGen Innovations",
    phone_no: "+1-555-456-7890",
    email: "sophia.wilson@example.com",
    role: "HR Specialist",
  },
  {
    name: "David Lee",
    company: "Alpha Solutions",
    phone_no: "+1-555-876-5432",
    email: "david.lee@example.com",
    role: "Operations Manager",
  },
  {
    name: "Olivia Martinez",
    company: "Visionary Systems",
    phone_no: "+1-555-234-6789",
    email: "olivia.martinez@example.com",
    role: "Marketing Executive",
  },
  {
    name: "James Anderson",
    company: "Bright Tech Co.",
    phone_no: "+1-555-567-8901",
    email: "james.anderson@example.com",
    role: "DevOps Engineer",
  },
  {
    name: "Emma Thomas",
    company: "Greenfield Technologies",
    phone_no: "+1-555-678-1239",
    email: "emma.thomas@example.com",
    role: "Business Analyst",
  },
];

export const navLists = [
  { name: "Home", link: "" },
  { name: "Products", link: "products" },
  { name: "Customers", link: "customers" },
  { name: "Support", link: "support" },
  { name: "Login", link: "login" },
];
